### ISSUE TITLE
"/quick" command returns an error "Message is too long"

### ISSUE THREAD

**Issue by Eng3lS** [zeroone2numeral2/qbittorrent-bot#13]
> [2020-01-15 16:56:29,665][__main__][INFO] >>> /quick command from Sergey
[2020-01-15 16:56:32,596][utils.utils][INFO] >>> error while running handler callback: Message is too long
Traceback (most recent call last):
  File "/mnt/usbstorage/qbitbot/qbittorrent-bot/utils/utils.py", line 67, in wrapped
    return func(bot, update, *args, **kwargs)
  File "/mnt/usbstorage/qbitbot/qbittorrent-bot/main.py", line 416, in on_quick_info_command
    update.message.reply_html(text, reply_markup=kb.QUICK_MENU_BUTTON)
  File "/mnt/usbstorage/qbitbot/lib/python3.6/site-packages/telegram/message.py", line 496, in reply_html
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/mnt/usbstorage/qbitbot/qbittorrent-bot/utils/utils.py", line 129, in wrapped
    return func(*args, **kwargs)
  File "/mnt/usbstorage/qbitbot/qbittorrent-bot/main.py", line 52, in send_message
    return super(CustomBot, self).send_message(*args, **kwargs)
  File "/mnt/usbstorage/qbitbot/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/mnt/usbstorage/qbitbot/lib/python3.6/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/mnt/usbstorage/qbitbot/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/mnt/usbstorage/qbitbot/lib/python3.6/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message is too long
[2020-01-15 16:58:18,723][__main__][INFO] >>> executing completed job 
![2020-01-15_172104](https://user-images.githubusercontent.com/59923611/72441343-910a3a00-37bb-11ea-876a-09a9c4c97400.png)
qBittorrent v4.2.1 with 810 torrents, 1 active
![2020-01-15_172706](https://user-images.githubusercontent.com/59923611/72441773-4a690f80-37bc-11ea-9023-eae584f0c4b3.png)

**Comment by zeroone2numeral2** [comment]
Hmm, yes. That's probably because you have a load of completed torrents. Will add a check to not show the completed torrents list if it's too long

**Comment by zeroone2numeral2** [comment]
Closed by 76258a12
