### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by ZChuckMoris** [zeroone2numeral2/qbittorrent-bot#6]
Hi. I configured proxy and it works ok, but 50/50 times I am getting timeout error in service's output and in telegram message from bot. How can i fix this?

![image](https://user-images.githubusercontent.com/18584322/70200168-a6079e00-1724-11ea-9101-84cd03f0b93d.png)

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/utils/request.py", line 203, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 359, in urlopen
    return super(ProxyManager, self).urlopen(method, url, redirect=redirect, **kw)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
    exc_cls=ReadTimeoutError)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/qbittorrent-bot/utils/utils.py", line 66, in wrapped
    return func(bot, update, *args, **kwargs)
  File "/home/pi/qbittorrent-bot/main.py", line 346, in on_torrents_list_selection
    update.message.reply_html('\n'.join(strings_chunk), disable_web_page_preview=True, reply_markup=markup)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/message.py", line 496, in reply_html
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/utils/request.py", line 205, in _request_wrapper
    raise TimedOut()
telegram.error.TimedOut: Timed out
[2019-12-05 07:35:19,877][__main__][INFO] >>> torrents list menu button from Moris: /all
[2019-12-05 07:35:19,878][__main__][INFO] >>> torrents status: all
[2019-12-05 07:35:19,905][__main__][INFO] >>> qbittirrent request returned 8 torrents
```

**Comment by zeroone2numeral2** [comment]
I get a timeout error too when my home connection is slow. This error is raised by python-telegram-bot when the connection it establishes with the API times out. The `send_message` request allows to pass a `timeout` value that will make the bot send the request to the API using the custom amount of seconds you passed. I am using it to send the json file in response to `/json`, you can see it [here](https://github.com/zeroone2numeral2/qbittorrent-bot/blob/9d5d177c6594c60e01d15efdecdd8febf8192aca/main.py#L366).

Myabe I'll add a new config value to set a program-level timeout for `send_message` requests
