### ISSUE TITLE
cant run docker image

### ISSUE THREAD

**Issue by Rebell81** [zeroone2numeral2/qbittorrent-bot#68]
Trying to run docker image, builded locally

with 
`docker build . -t qbittelegrambot`

and here is...

```
PS C:\Users\shark\Documents\repos\qbittorrent-bot> docker run -v ${PWD}/config.toml:/app/config.toml qbittelegrambot
/usr/local/lib/python3.12/site-packages/telegram/utils/request.py:54: UserWarning: python-telegram-bot wasn't properly installed. Please refer to README.rst on how to properly install.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/telegram/utils/request.py", line 36, in <module>
    import telegram.vendor.ptb_urllib3.urllib3 as urllib3
  File "/usr/local/lib/python3.12/site-packages/telegram/vendor/ptb_urllib3/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.12/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/local/lib/python3.12/site-packages/telegram/vendor/ptb_urllib3/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'telegram.vendor.ptb_urllib3.urllib3.packages.six.moves'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 3, in <module>
    import bot
  File "/app/bot/__init__.py", line 8, in <module>
    from .updater import updater
  File "/app/bot/updater.py", line 2, in <module>
    from telegram.ext import Defaults
  File "/usr/local/lib/python3.12/site-packages/telegram/__init__.py", line 174, in <module>
    from .bot import Bot
  File "/usr/local/lib/python3.12/site-packages/telegram/bot.py", line 103, in <module>
    from telegram.utils.request import Request
  File "/usr/local/lib/python3.12/site-packages/telegram/utils/request.py", line 44, in <module>
    import urllib3.contrib.appengine as appengine  # type: ignore[no-redef]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'urllib3.contrib.appengine'
```

im tried to add `RUN pip3 install urllib3` to **DOCKERFILE** but still got this exception

**Comment by Rebell81** [comment]
here is solution ....

https://github.com/zeroone2numeral2/qbittorrent-bot/pull/69
