### ISSUE TITLE
Doesn't work after updating to new version

### ISSUE THREAD

**Issue by ZChuckMoris** [zeroone2numeral2/qbittorrent-bot#9]
Hi. Tried to get new files from Github repo via git clone to try what's new here, but i am getting troubles, launching it, even though with previous version everything worked ok. After testing and understanding, that new version doesn't work on my Raspberry Pi, reverted back to previous one (good that i have backed it up).

Check output:
```
(venv) pi@RaspberryPi4:~/qbittorrent-bot $ python3 main.py
[2019-12-18 03:15:20,988][telegram.ext.updater][WARNING] >>> Connection pool of Request object is smaller than optimal value (5)
[2019-12-18 03:15:22,763][telegram.vendor.ptb_urllib3.urllib3.connectionpool][WARNING] >>> Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xf639e270>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot980791505:************************/getMe
[2019-12-18 03:15:22,791][telegram.vendor.ptb_urllib3.urllib3.connectionpool][WARNING] >>> Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xf639e3b0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot980791505:************************/getMe
[2019-12-18 03:15:22,801][telegram.vendor.ptb_urllib3.urllib3.connectionpool][WARNING] >>> Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xf639e450>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot980791505:************************/getMe
Traceback (most recent call last):
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
telegram.vendor.ptb_urllib3.urllib3.exceptions.NewConnectionError: <telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xf639e4f0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/utils/request.py", line 203, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
telegram.vendor.ptb_urllib3.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot980791505:************************/getMe (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xf639e4f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 61, in <module>
    qb = CustomClient(config.qbittorrent.url, bot_username=updater.bot.username)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/bot.py", line 51, in decorator
    self.get_me()
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/bot.py", line 204, in get_me
    result = self._request.get(url, timeout=timeout)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/utils/request.py", line 253, in get
    result = self._request_wrapper('GET', url, **urlopen_kwargs)
  File "/home/pi/qbittorrent-bot/venv/lib/python3.7/site-packages/telegram/utils/request.py", line 209, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot980791505:************************/getMe (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xf639e4f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

and here is what i am getting with previous version (everything seems to be ok):
```
Dec 18 03:21:34 RaspberryPi4 systemd[1]: Started qBittorrent API's Telegram interface.
Dec 18 03:21:41 RaspberryPi4 python3[2047]: [2019-12-18 03:21:41,116][__main__][INFO] >>> registering handlers...
Dec 18 03:21:41 RaspberryPi4 python3[2047]: [2019-12-18 03:21:41,124][__main__][INFO] >>> registering "completed torrents" job
Dec 18 03:21:41 RaspberryPi4 python3[2047]: [2019-12-18 03:21:41,151][__main__][INFO] >>> starting as @qBittorrent_ShalonHDD_bot
Dec 18 03:21:59 RaspberryPi4 python3[2047]: [2019-12-18 03:21:59,087][__main__][INFO] >>> torrents list menu button from Морис: /all
Dec 18 03:21:59 RaspberryPi4 python3[2047]: [2019-12-18 03:21:59,088][__main__][INFO] >>> torrents status: all
Dec 18 03:21:59 RaspberryPi4 python3[2047]: [2019-12-18 03:21:59,121][__main__][INFO] >>> qbittirrent request returned 21 torrents
Dec 18 03:23:41 RaspberryPi4 python3[2047]: [2019-12-18 03:23:41,152][__main__][INFO] >>> executing completed job
Dec 18 03:25:41 RaspberryPi4 python3[2047]: [2019-12-18 03:25:41,152][__main__][INFO] >>> executing completed job
```

**Comment by zeroone2numeral2** [comment]
Ugh, thanks. I pushed these while I was at work but I haven't been able to try it at home yet. I suggest you to revert your local code to an old commit until I fix this :(

**Comment by zeroone2numeral2** [comment]
@ZChuckMoris I've only now looked at your report and logs and it looks like it's not a bug with the code but rather the process is not able to connect to the internet :/

it looks like a problem with your network

**Comment by ZChuckMoris** [comment]
@zeroone2numeral2 , nope. There aren't any problems with my internet connection. Every time I am trying to start this new version, I am getting such and error, while there are none with previous one.
Maybe it's because i am using proxy and there are some troubles with proxy in this version?

I have set it programmatically, following [official python-telegram-bot documentation](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy), which you shared.

**Comment by zeroone2numeral2** [comment]
@ZChuckMoris that's weird. Are you able to ping api.telegram.org when the proxy is active system-wide?

**Comment by ZChuckMoris** [comment]
@zeroone2numeral2 
I can't ping api.telegram.org from Terminal, but i can use proxy through Privoxy to bypass this page block in Russia. Check the screenshots: everything works from browser, but not from Terminal.
![image](https://user-images.githubusercontent.com/18584322/71362110-3576d300-25a6-11ea-8fc6-f47d00cc8420.png)
![image](https://user-images.githubusercontent.com/18584322/71362056-02ccda80-25a6-11ea-80d8-5bc302996b5a.png)

**Comment by zeroone2numeral2** [comment]
Is this still an issue?

**Comment by ZChuckMoris** [comment]
@zeroone2numeral2, I rolled back after to previous version (before 18th december) to get everything working. Now i updated to latest git version again and i am getting error. Here is the output:
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import bot
  File "/opt/qbittorrent-bot-new/bot/__init__.py", line 36, in <module>
    qb = CustomClient(config.qbittorrent.url, bot_username=updater.bot.username)
  File "/opt/qbittorrent-bot-new/qbt/custom.py", line 120, in __init__
    super(CustomClient, self).__init__(url=url)
  File "/opt/qbittorrent-bot-new/venv/lib/python3.7/site-packages/qbittorrent/client.py", line 30, in __init__
    """)
RuntimeError:
                This wrapper only supports qBittorrent applications
                 with version higher than 3.1.x.
                 Please use the latest qBittorrent release.

```

**Comment by zeroone2numeral2** [comment]
@ZChuckMoris latest version of `python-qbittorrent` does no longer support qBittorrent 3.1

You have to roll back to python-qbittorrent 0.3.1 (`pip install python-qbittorrent==0.3.1`)

**Comment by ZChuckMoris** [comment]
@zeroone2numeral2, actually, my version of qbittorrent is 4.2.0
![image](https://user-images.githubusercontent.com/18584322/78460520-238aed00-76ca-11ea-9b6c-77c65e693f4a.png)

**Comment by ZChuckMoris** [comment]
@zeroone2numeral2, ok, i understand now, what's the reason: in requirements.txt there was specified 0.3.1 version of `python-qbittorrent` package. So that's why it didn't work with 4.2+ version of qbittorrent. I updated python-qbittorrent package through `pip install --upgrade python-qbittorrent` and now everything works like a charm.
Say, please, if I also have to update `python-telegram-bot` from 11.1.0 to 12.5.1

**Comment by ZChuckMoris** [comment]
Ok, now there is another problem: I am not able to start qbittorrent-bot from any other place, except bot's root path directory. For example, i am unable to start it from my user's home path. Also I am not able to start it using systemd with `WorkingDirectory=/opt/qbittorrent-bot` specified.
Here is the output when starting from `/home/ubuntu` path (ubuntu is my username).
```
ubuntu@ubuntu:/home/ubuntu$ /opt/qbittorrent-bot/venv/bin/python3 /opt/qbittorrent-bot/main.py
Traceback (most recent call last):
  File "/opt/qbittorrent-bot/main.py", line 1, in <module>
    import bot
  File "/opt/qbittorrent-bot/bot/__init__.py", line 9, in <module>
    from .bot import CustomBot
  File "/opt/qbittorrent-bot/bot/bot.py", line 12, in <module>
    from utils import u
  File "/opt/qbittorrent-bot/utils/__init__.py", line 1, in <module>
    from utils import utils as u
  File "/opt/qbittorrent-bot/utils/utils.py", line 9, in <module>
    from .permissions_storage import permissions
  File "/opt/qbittorrent-bot/utils/permissions_storage.py", line 19, in <module>
    permissions = Permissions('permissions.json', autosave=True)
  File "/opt/qbittorrent-bot/utils/permissions_storage.py", line 13, in __init__
    with open('default_permissions.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'default_permissions.json'
```

**Comment by zeroone2numeral2** [comment]
@ZChuckMoris this might be a stupid question, but did you check if `default_permissions.json` exists in the directory?

**Comment by ZChuckMoris** [comment]
@zeroone2numeral2, yup, here it is.
![image](https://user-images.githubusercontent.com/18584322/78539863-eaeb3080-77fb-11ea-9d28-b41a11cd6e8a.png)
Temporarily rename qbittorrent-bot to qbittorrent-bot-new to continue using old version, while i can't launch the new one on startup.
![image](https://user-images.githubusercontent.com/18584322/78539888-f6d6f280-77fb-11ea-90a4-7a35009701dc.png)
In the old version this file is also in place

**Comment by zeroone2numeral2** [comment]
> Say, please, if I also have to update python-telegram-bot from 11.1.0 to 12.5.1

I didn't answer to this: nope. I'm planning to move to ptb 12 (#20) bot not soon

**Comment by ZChuckMoris** [comment]
@zeroone2numeral2, how do you run the last git as systemd service?

**Comment by ZChuckMoris** [comment]
> I didn't answer to this: nope. I'm planning to move to ptb 12 (#20) bot not soon
@zeroone2numeral2, ok, i didn't update it yet, so that's not the problem. Also, there are no problems if i first `cd` into the program's folder and than start it from there. I have problems only when i start it from any other place using absolute path of `python3` and `main.py`. Hope, you will tell, what am i doing wrong.

**Comment by zeroone2numeral2** [comment]
I'll have to check what's wrong directly from my machine. I have abandoned systemd as default method to run this bot a long time ago (now I'm using [supervisor](http://supervisord.org/index.html)) so I haven't experienced this issue myself. As long as `WorkingDirectory` is correctly set in your service file, it shouldn't have this kind of problems. I should have a look at how it behaves on my raspberry

**Comment by zeroone2numeral2** [comment]
Tested using systemd and looks like there's no issue when `WorkingDirectory` is correctly set. Are you still facing this?

**Comment by ZChuckMoris** [comment]
Checked previous version (which i tested in April): nothing worked. Removed it, downloaded new one using git clone and seems like it is working. The only thing i don't understand right now is how to use my proxy with this version. I will search for proxy guide, test it and if everything is ok, i will close this issue.

**Comment by zeroone2numeral2** [comment]
You can refer to [python-telegram.bot's wiki guide](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy) about proxies. You should pass the example's `REQUEST_KWARGS` in this line:

https://github.com/zeroone2numeral2/qbittorrent-bot/blob/0ed06974e5940e9ba40ec8ffc98596554bf7ba30/bot/updater.py#L9

**Comment by ZChuckMoris** [comment]
@zeroone2numeral2, i already tried it, but nothing worked yet

**Comment by ZChuckMoris** [comment]
Tested now: i am not sure, what has actuallu changed, but everything is working well right now even with proxy. Thank you very much for your work!

**Comment by zeroone2numeral2** [comment]
Glad it finally worked out lol. Sorry if I haven't been much of an help
